// ! Auth login
export const AUTH_LOGIN_FETCH = 'AUTH_LOGIN_FETCH';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

// ! Auth Registration 
export const AUTH_REGISTRATION_FETCH = 'AUTH_REGISTRATION_FETCH';
export const AUTH_REGISTRATION_SUCCESS = 'AUTH_REGISTRATION_SUCCESS';
export const AUTH_REGISTRATION_FAILURE = 'AUTH_REGISTRATION_FAILURE';

// ! Get Task
export const GET_TASK_FETCH = 'GET_TASK_FETCH';
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAILURE = 'GET_TASK_FAILURE';
// ! Post Task
export const POST_TASK_FETCH = 'POST_TASK_FETCH';
export const POST_TASK_SUCCESS = "POST_TASK_SUCCESS";
export const POST_TASK_FAILURE = 'POST_TASK_FAILURE';

// ! Delete Task
export const DELETE_TASK_FETCH = 'DELETE_TASK_FETCH';
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';